version: '3.8'
volumes:
  static:
services:
  api:
    container_name: api
    environment:
      PORT: ${PORT}
      API: ${API}
      DSN: ${DSN}
      MODE: ${MODE}
    build:
      context: .
    ports:
      - '3000:3000'
networks:
  default:
    external:
      name: timeweeb
